apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  annotations:
    argocd-image-updater.argoproj.io/image-list: wisecow=saurabhkr952/wisecow
    argocd-image-updater.argoproj.io/write-back-method: git
    argocd-image-updater.argoproj.io/wisecow.update-strategy: newest-build    
  name: wisecow
  namespace: argocd
spec:
  destination:
    namespace: default
    server: https://kubernetes.default.svc
  project: default
  source:
    path: gitops
    repoURL: https://github.com/saurabhkr952/accuknox-submission.git
    targetRevision: HEAD
  syncPolicy:
    automated:
      selfHeal: true
      prune: true
    syncOptions:
      - CreateNamespace=true