apiVersion: apps/v1
kind: Deployment
metadata:
  name: wisecow-deployment
  namespace: wisecow
spec:
  replicas: 2
  selector:
    matchLabels:
      app: wisecow
  template:
    metadata:
      labels:
        app: wisecow
    spec:
      containers:
        - name: wisecow
          image: harishasapu/wisecow:ed1b6490e4de8f9e4c0efab940fe5dc0d5cb16b8
          ports:
            - containerPort: 4499
