apiVersion: apps/v1
kind: Deployment
metadata:
  name: wisecow-deployment
  namespace: wisecow
spec:
  replicas: 1
  selector:
    matchLabels:
      app: wisecow
  template:
    metadata:
      labels:
        app: wisecow
    spec:
      containers:
        - name: wisecow
          image: harishasapu/wisecow:d3bad0b7e529f8312512c5bf0dd59462402cd15e
          ports:
            - containerPort: 4499
