apiVersion: apps/v1
kind: Deployment
metadata:
  name: wisecow-deployment
  namespace: wisecow
spec:
  replicas: 1
  selector:
    matchLabels:
      app: wisecow
  template:
    metadata:
      labels:
        app: wisecow
    spec:
      containers:
        - name: wisecow
          image: harishasapu/wisecow:a811ca4e37362cda8511fd12a674db54ab57c5e7
          ports:
            - containerPort: 4499
